const fs = require('fs');

// Generate a simple text file
const content = 'This is a sample artifact generated by the JavaScript script.';

fs.writeFileSync('artifact.txt', content, 'utf8');

console.log('Artifact created: artifact.txt');
